add_library(fd_recording STATIC src/recording.cpp src/optimal_lap.cpp)
target_include_directories(fd_recording PUBLIC include)
target_link_libraries(fd_recording PUBLIC fd_simulation)
target_compile_features(fd_recording PUBLIC cxx_std_20)
if(MSVC)
  target_compile_options(fd_recording PRIVATE /W4 /permissive- /utf-8)
else()
  target_compile_options(fd_recording PRIVATE -Wall -Wextra -Wpedantic)
endif()
