name: C++ core

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core:
    name: Core / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            preset: linux-core
          - os: windows-2022
            preset: windows-core
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Configure
        run: cmake --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} --parallel
      - name: Test
        run: ctest --preset ${{ matrix.preset }} --output-on-failure --no-tests=error

